name: xstream
description: A cross-platform network accelerator powered by XTLS VLESS.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2      # 管理全局状态的插件
  http: ^1.2.2          # 网络请求
  path_provider: ^2.1.5 # 访问文件系统
  process_run: ^1.2.4  # 执行 shell 命令和管理权限
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # 注册外部资源
  assets:
    - assets/logo.png
    - assets/vpn_nodes.json
    - assets/xray-template.json
